/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Yolala1232 (https://sketchfab.com/Yolala1232)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-dell-latitude-5400-c3dfc53a600e427c9db9be83aec9860d
Title: Laptop Dell Latitude 5400
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { useLoader } from "@react-three/fiber";
function Laptop(props) {
  const { nodes, materials } = useGLTF("/models/laptop.glb");
  const laptopRef = useRef();
  // console.log(materials["8th_gen_core_i5_logo"]);
  const [targetRotation, setTargetRotation] = useState(0);
  const [currentRotation, setCurrentRotation] = useState(Math.PI / 2);

  const coretexture = useLoader(
    THREE.TextureLoader,
    "models/textures/8th_gen_core_i5_logo_diffuse.png"
  );
  const delltexture = useLoader(
    THREE.TextureLoader,
    "models/textures/delllogo3_diffuse.png"
  );
  const screenRef = useRef();
  const backpanelRef = useRef();
  const [showScreen, setShowScreen] = useState(false);

  useFrame(() => {
    const rotationSpeed = 0.01;

    if (currentRotation > targetRotation) {
      setCurrentRotation((prev) =>
        Math.max(prev - rotationSpeed, targetRotation)
      );
    }

    if (backpanelRef.current) {
      backpanelRef.current.rotation.z = currentRotation;
    }

    if (!showScreen && currentRotation === targetRotation) {
      setShowScreen(true);
    }

    if (screenRef.current && showScreen) {
      screenRef.current.rotation.z = currentRotation;
    }
  });

  return (
    <group
      {...props}
      ref={laptopRef}
      dispose={null}
      position={[0.5, -2.5, -1.7]}
      rotation={[0, Math.PI / 2, 0]}
    >
      <group
        position={[0.29150194, 0.36141503, -0.5051024]}
        rotation={[0, 0, -2.94960644]}
        scale={[-0.17841202, 0.10539534, 1.66856682]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.Material}
          onUpdate={(self) => {
            self.material.metalness = 1.25;
            self.material.roughness = 0.2;
            self.material.emissive.set("black");
          }}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials["Material.025"]}
        />
      </group>
      <group
        ref={backpanelRef}
        position={[1.25290799, 0.40563738, -0.55241054]}
      >
        <group
          position={[0, 0.01, 0]} // adjust this value depending on the model height
          rotation={[0, 0, 2.89662926]}
          scale={[-0.06722913, 0.06578676, 0.14393996]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_360.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_361.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_362.geometry}
            material={materials.dell_logo2edited}
            onUpdate={(self) => {
              self.material.metalness = 1.2; // Higher metalness for a shiny effect
              self.material.roughness = 0.2; // Low roughness for a smooth finish
            }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_363.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_364.geometry}
            material={materials.delllogo3}
            onUpdate={(self) => {
              self.material.metalness = 2;
              self.material.map = delltexture; // Overlay image on top of existing material
              self.material.needsUpdate = true; // Ensure the update applies
            }}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["8th_gen_core_i5_logo"]} // Keep existing material
        position={[-0.57604873, 0.43941298, 0.64202666]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1316313}
        onUpdate={(self) => {
          self.material.metalness = 1.2;
          self.material.map = coretexture; // Overlay image on top of existing material
          self.material.needsUpdate = true; // Ensure the update applies
        }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials["Material.003"]}
        position={[1.101197, 0.39518154, -2.00022125]}
        scale={[0.06904752, 0.00775628, 0.09916546]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials["Material.008"]}
        position={[0.89845443, 0.39583784, -1.99197924]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.0418928, 0.01360122, 0.01561292]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials["Material.011"]}
        position={[0.57703495, 0.38918582, -1.97719789]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.26430804, 0.18212911, 0.04090466]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials["Material.005"]}
        position={[0.89718479, 0.4014132, -1.96674383]}
        scale={[0.03884065, 0.00441417, 0.03884065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials["Material.004"]}
        position={[0.07378352, 0.37837887, -1.96400547]}
        rotation={[0.00169065, 0.00049851, -2.94330515]}
        scale={[-0.16417105, 0.10477468, 1.6226083]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Material}
        position={[1.05312634, 0.39103907, 0.80030137]}
        rotation={[0, 0, -2.94960644]}
        scale={[-0.17636167, 0.0827854, 1.6226083]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42144355, -1.75240505]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials["Material.011"]}
        position={[-0.37979415, 0.38918582, -1.93137765]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.30514684, 0.18212909, 0.02467903]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42144355, -1.58635664]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42144355, -1.41546929]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -1.24846911]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -1.08341277]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -0.915088]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -0.74919826]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -0.58451039]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -0.41873172]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -0.25299954]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, -0.08713885]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, 0.07976915]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, 0.24418582]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, 0.41029885]}
        scale={[0.04830702, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials["Material.007"]}
        position={[1.04847777, 0.42086303, 0.57229614]}
        scale={[0.04830702, 0.11229598, 0.07458705]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials["Material.007"]}
        position={[0.18051244, 0.42076775, -0.66037238]}
        scale={[0.07238398, 0.10572948, 0.41890806]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42144355, -1.74953079]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42144355, -1.57812929]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42144355, -1.40779269]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -1.23950326]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -1.067222]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -0.89582992]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -0.720649]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -0.54925692]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -0.37892964]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -0.20753755]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, -0.03528942]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, 0.13609792]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, 0.30660036]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials["Material.007"]}
        position={[0.89971954, 0.42086303, 0.52798975]}
        scale={[0.06881779, 0.11643202, 0.11898851]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials["Material.007"]}
        position={[0.71377873, 0.42234477, -1.69748461]}
        scale={[0.06975071, 0.12105088, 0.11974589]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials["Material.007"]}
        position={[0.53908676, 0.42085245, -1.67835128]}
        scale={[0.06968973, 0.128573, 0.14607348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials["Material.007"]}
        position={[0.36132389, 0.4206081, -1.63768446]}
        scale={[0.0693291, 0.13061048, 0.1852515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials["Material.007"]}
        position={[0.17901343, 0.4206081, -1.72680449]}
        scale={[0.06731856, 0.12105088, 0.09491101]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -1.48074126]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -1.30933976]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -1.13900316]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -0.97071373]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -0.79843247]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -0.62704039]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -0.4518595]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -0.28046742]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, -0.11014014]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, 0.06125195]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, 0.23350008]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, 0.40488744]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials["Material.007"]}
        position={[0.71487832, 0.42234477, 0.57538986]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials["Material.007"]}
        position={[0.53936464, 0.4206135, 0.52415401]}
        scale={[0.06968973, 0.128573, 0.12084774]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.42085245, -1.42406499]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.42085245, -1.25266349]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.42085245, -1.08232689]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.42085245, -0.91403741]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, -0.74175614]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, -0.57036406]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, -0.39518318]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, -0.22379111]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, -0.05346383]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, 0.11792827]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials["Material.007"]}
        position={[0.53788155, 0.4206135, 0.29017639]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials["Material.007"]}
        position={[0.36132389, 0.42106566, 0.47633561]}
        scale={[0.0693291, 0.13061048, 0.16748814]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42187265, -1.34210455]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42154381, -1.17070305]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42154381, -1.00036645]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42154381, -0.83207697]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42154381, -0.6597957]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42106566, -0.48840362]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42106566, -0.31322274]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42106566, -0.14183067]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42106566, 0.02849661]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials["Material.007"]}
        position={[0.36048469, 0.42106566, 0.19988871]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials["Material.007"]}
        position={[0.18052334, 0.42061532, -1.51747108]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials["Material.007"]}
        position={[0.18052334, 0.42061532, -1.34339619]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials["Material.007"]}
        position={[0.18052334, 0.42061532, -1.17305911]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials["Material.007"]}
        position={[0.1827883, 0.42106566, -0.14183067]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials["Material.007"]}
        position={[0.1827883, 0.42106566, 0.02849661]}
        scale={[0.06881779, 0.11643202, 0.07263999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials["Material.007"]}
        position={[0.20452416, 0.42106566, 0.20001546]}
        scale={[0.04435033, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials["Material.007"]}
        position={[0.07906878, 0.42106566, 0.20292176]}
        scale={[0.04435033, 0.11229598, 0.07365239]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_178.geometry}
        material={materials["Material.007"]}
        position={[0.07906878, 0.42106566, 0.38500974]}
        scale={[0.04435033, 0.11229598, 0.07365239]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials["Material.007"]}
        position={[0.07906878, 0.42059821, 0.56783962]}
        scale={[0.04435033, 0.11229598, 0.07365239]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials["Material.007"]}
        position={[0.20465392, 0.42106566, 0.38500452]}
        scale={[0.04435033, 0.11229598, 0.07365239]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials["Material.007"]}
        position={[0.20452416, 0.42059821, 0.56911892]}
        scale={[0.04435033, 0.11229598, 0.07120106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, 0.29086801]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, 0.11802065]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -0.05260769]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_192.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -0.22278836]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_194.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -0.39467499]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_196.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -0.57000279]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_198.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -0.74195004]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_200.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -0.9151274]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_202.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -1.08244109]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -1.25206637]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_206.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -1.42519498]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_208.geometry}
        material={materials["Material.012"]}
        position={[0.36092868, 0.4218851, -1.34205937]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_210.geometry}
        material={materials["Material.012"]}
        position={[0.18008827, 0.4218851, -0.65887386]}
        scale={[0.0651479, 0.01776287, 0.40755862]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_212.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -1.17021]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_214.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -0.99810088]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_216.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -0.8309865]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_218.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -0.6585272]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_220.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -0.48779982]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_222.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -0.31350839]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_224.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, -0.14174172]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_226.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, 0.02989694]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_228.geometry}
        material={materials["Material.012"]}
        position={[0.53923804, 0.4218851, 0.52523315]}
        scale={[0.06501041, 0.01772538, 0.11129157]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_230.geometry}
        material={materials["Material.012"]}
        position={[0.36138776, 0.4218851, 0.20017776]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_232.geometry}
        material={materials["Material.012"]}
        position={[0.36265758, 0.4218851, 0.4777284]}
        scale={[0.06501041, 0.01772538, 0.15761335]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_234.geometry}
        material={materials["Material.012"]}
        position={[0.18295668, 0.4218851, -0.14174172]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_236.geometry}
        material={materials["Material.012"]}
        position={[0.18295668, 0.4218851, 0.03089021]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_238.geometry}
        material={materials["Material.012"]}
        position={[0.20532084, 0.4218851, 0.19951817]}
        scale={[0.03999436, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_240.geometry}
        material={materials["Material.012"]}
        position={[0.20532084, 0.4218851, 0.3849079]}
        scale={[0.0416114, 0.01844205, 0.0676389]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_242.geometry}
        material={materials["Material.012"]}
        position={[0.07982245, 0.4218851, 0.3849079]}
        scale={[0.0416114, 0.01844205, 0.0676389]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_244.geometry}
        material={materials["Material.012"]}
        position={[0.07982245, 0.4218851, 0.5673613]}
        scale={[0.0416114, 0.01844205, 0.0676389]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_246.geometry}
        material={materials["Material.012"]}
        position={[0.07992036, 0.4218851, 0.2038206]}
        scale={[0.0416114, 0.01844205, 0.0676389]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_248.geometry}
        material={materials["Material.012"]}
        position={[0.20532084, 0.4218851, 0.56974584]}
        scale={[0.03999436, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_250.geometry}
        material={materials["Material.012"]}
        position={[0.17936902, 0.4218851, -1.34205937]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_252.geometry}
        material={materials["Material.012"]}
        position={[0.17936902, 0.4218851, -1.1717788]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_254.geometry}
        material={materials["Material.012"]}
        position={[0.17936902, 0.4218851, -1.5181607]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials["Material.012"]}
        position={[0.17936902, 0.4218851, -1.72623563]}
        scale={[0.06501041, 0.01772538, 0.08742668]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_258.geometry}
        material={materials["Material.012"]}
        position={[0.36092868, 0.4218851, -1.63814723]}
        scale={[0.06501041, 0.01772538, 0.17843835]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_260.geometry}
        material={materials["Material.012"]}
        position={[0.53791893, 0.4218851, -1.67965245]}
        scale={[0.06501041, 0.01772538, 0.13911849]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_262.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -1.06831014]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_264.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -1.69814706]}
        scale={[0.06501041, 0.01772538, 0.11345947]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_266.geometry}
        material={materials["Material.023"]}
        position={[0.43818784, 0.33282247, -0.47992516]}
        scale={[2.49579358, 4.1545372, 4.1545372]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_268.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -1.30858421]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_270.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -1.13786018]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_272.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -0.97017515]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_274.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -0.79685998]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_276.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -0.62548482]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_278.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -0.45208579]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_280.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -0.28021675]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_282.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -0.1091855]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_284.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, 0.06187487]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_286.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, 0.23303123]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_288.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, 0.40470302]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_290.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, 0.57585937]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_292.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -0.89567894]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_294.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -0.71989775]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_296.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -0.54912263]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_298.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -0.37886211]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_300.geometry}
        material={materials["Material.012"]}
        position={[0.71375281, 0.4218851, -1.48036051]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_302.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -1.7506218]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_304.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -1.57799053]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_306.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -1.40643728]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_308.geometry}
        material={materials["Material.012"]}
        position={[0.90075499, 0.4218851, -1.23923767]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_310.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -0.20928991]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_312.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, -0.03350872]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_314.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, 0.1372664]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_316.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, 0.30752692]}
        scale={[0.06501041, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_318.geometry}
        material={materials["Material.012"]}
        position={[0.89969039, 0.4218851, 0.52820885]}
        scale={[0.06501041, 0.01772538, 0.1107064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_320.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, 0.24588811]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_322.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, 0.41024911]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_324.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, 0.57282805]}
        scale={[0.04312713, 0.01772538, 0.06978443]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_326.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, 0.08127871]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_328.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -0.0870164]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_330.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -0.25345472]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_332.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -0.41668171]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_334.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -0.58403826]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_336.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -0.74909496]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_338.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -0.91567147]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_340.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -1.0842489]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_342.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -1.24934232]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_344.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -1.41431081]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_346.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -1.58667696]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_348.geometry}
        material={materials["Material.012"]}
        position={[1.04750395, 0.4218851, -1.75163245]}
        scale={[0.04312713, 0.01772538, 0.06501041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_350.geometry}
        material={materials["Material.014"]}
        position={[0.19565549, 0.42924637, -1.36408544]}
        scale={0.13349414}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_352.geometry}
        material={materials["Material.015"]}
        position={[0.19734862, 0.43016526, -1.33060992]}
        scale={0.13349414}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_354.geometry}
        material={materials["Material.016"]}
        position={[0.17331262, 0.42486459, -1.33297944]}
        scale={0.13349414}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_356.geometry}
        material={materials["Material.017"]}
        position={[0.17465024, 0.42470884, -1.36397278]}
        scale={0.13349414}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_358.geometry}
        material={materials["Material.019"]}
        position={[0.57522523, 0.44139826, -1.57422698]}
        scale={0.00435101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_366.geometry}
        material={materials["Material.020"]}
        position={[0.45740783, 0.40620729, -0.65557903]}
        scale={[0.03853811, 0.03737701, 0.03853811]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_368.geometry}
        material={materials["Material.021"]}
        position={[0.20824786, 0.44089836, 0.3863056]}
        scale={0.34334549}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_370.geometry}
        material={materials["Material.021"]}
        position={[0.07957784, 0.44068891, 0.20053357]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.34334549}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_372.geometry}
        material={materials["Material.021"]}
        position={[0.07989138, 0.44133729, 0.56881708]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.34334549}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_374.geometry}
        material={materials["Material.021"]}
        position={[0.07945693, 0.44099265, 0.3863056]}
        rotation={[-Math.PI, -3.3e-7, -Math.PI]}
        scale={0.34334549}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_376.geometry}
        material={materials["Material.018"]}
        position={[0.79927206, 0.39967209, -2.00841093]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.08376703}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_378.geometry}
        material={materials["Material.018"]}
        position={[0.75909549, 0.41820538, 0.91443592]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.08376703}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_380.geometry}
        material={materials.material_0}
        position={[1.0005312, 0.37519482, 0.88358092]}
        scale={[0.03119971, 0.02165976, 0.03119971]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_382.geometry}
        material={materials["Material.022"]}
        position={[1.00047553, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_384.geometry}
        material={materials["Material.011"]}
        position={[1.00329041, 0.37059134, 0.86349976]}
        rotation={[1.65806276, 0, 0]}
        scale={[0.04991189, 0.08093754, 0.0252533]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_386.geometry}
        material={materials["Material.022"]}
        position={[1.00509334, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_388.geometry}
        material={materials["Material.022"]}
        position={[1.0093317, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_390.geometry}
        material={materials["Material.022"]}
        position={[1.01350605, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_392.geometry}
        material={materials["Material.022"]}
        position={[1.01775026, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_394.geometry}
        material={materials["Material.022"]}
        position={[1.02229667, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_396.geometry}
        material={materials["Material.022"]}
        position={[1.02679098, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_398.geometry}
        material={materials["Material.022"]}
        position={[0.99629056, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_400.geometry}
        material={materials["Material.022"]}
        position={[0.99198449, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_402.geometry}
        material={materials["Material.022"]}
        position={[0.98726445, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_404.geometry}
        material={materials["Material.022"]}
        position={[0.98334193, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_406.geometry}
        material={materials["Material.022"]}
        position={[0.97938776, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_408.geometry}
        material={materials["Material.022"]}
        position={[0.97532707, 0.39991567, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00981552, 0.00124301, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_410.geometry}
        material={materials["Material.018"]}
        position={[0.64671522, 0.41820538, 0.91443592]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.08376703}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_412.geometry}
        material={materials.material_0}
        position={[0.89806503, 0.3848601, 0.88358092]}
        scale={[0.03119971, 0.01035012, 0.03119971]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_414.geometry}
        material={materials["Material.011"]}
        position={[0.84252238, 0.37059134, 0.86349976]}
        rotation={[1.65806276, 0, 0]}
        scale={[0.25286612, 0.08093753, 0.0252533]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_416.geometry}
        material={materials["Material.022"]}
        position={[0.89881796, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_418.geometry}
        material={materials["Material.022"]}
        position={[0.90343577, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_420.geometry}
        material={materials["Material.022"]}
        position={[0.90767413, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_422.geometry}
        material={materials["Material.022"]}
        position={[0.91184849, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_424.geometry}
        material={materials["Material.022"]}
        position={[0.91609269, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_426.geometry}
        material={materials["Material.022"]}
        position={[0.9206391, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_428.geometry}
        material={materials["Material.022"]}
        position={[0.92513341, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_430.geometry}
        material={materials["Material.022"]}
        position={[0.894633, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_432.geometry}
        material={materials["Material.022"]}
        position={[0.89032692, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_434.geometry}
        material={materials["Material.022"]}
        position={[0.88560688, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_436.geometry}
        material={materials["Material.022"]}
        position={[0.88168436, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_438.geometry}
        material={materials["Material.022"]}
        position={[0.87773019, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_440.geometry}
        material={materials["Material.022"]}
        position={[0.87366951, 0.39286152, 0.87980407]}
        rotation={[0, 0, -1.60790125]}
        scale={[0.00479369, 0.00124236, 0.01505079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_442.geometry}
        material={materials.material_0}
        position={[0.79372227, 0.38446638, 0.88358092]}
        scale={[0.03756791, 0.01035012, 0.03119971]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_444.geometry}
        material={materials.material_0}
        position={[0.68028057, 0.38526142, 0.88358092]}
        scale={[0.03756791, 0.01035012, 0.03119971]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_446.geometry}
        material={materials["Material.027"]}
        position={[0.79335982, 0.39022547, 0.86769521]}
        rotation={[0, 0, 3.12194068]}
        scale={[0.03697229, 0.00346681, 0.04197053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_448.geometry}
        material={materials["Material.005"]}
        position={[0.67995298, 0.39022547, 0.86769521]}
        rotation={[0, 0, 3.12194068]}
        scale={[0.03697229, 0.00346681, 0.04197053]}
      />
      {showScreen && (
        <group ref={screenRef} position={[1.50639784, 1.35246623, -0.53393549]}>
          <group position={[0, 0.01, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_450.geometry}
              material={materials["Material.026"]}
              rotation={[0, 0, 2.89662926]}
              scale={[-0.06722913, 0.06578676, 0.14393996]}
            />
          </group>
        </group>
      )}

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_452.geometry}
        material={materials["Material.011"]}
        position={[0.29150194, 0.36141503, -0.5051024]}
        rotation={[0, 0, -2.94960644]}
        scale={[-0.17841202, 0.10539534, 1.66856682]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_454.geometry}
        material={materials["Material.011"]}
        position={[0.29150194, 0.36141503, -0.5051024]}
        rotation={[0, 0, -2.94960644]}
        scale={[-0.17841202, 0.10539534, 1.66856682]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_456.geometry}
        material={materials["Material.013"]}
        position={[0.6957379, 0.44088507, -1.50254583]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_458.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -1.33470249]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_460.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -1.15166032]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_462.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -0.98470736]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_464.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -0.81269377]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_466.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -0.64140999]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_468.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -0.46776849]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_470.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -0.28883618]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_472.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, -0.12957628]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_474.geometry}
        material={materials["Material.013"]}
        position={[0.69406039, 0.44088507, 0.04155146]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04950393}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_476.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -1.4400208]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_478.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -1.26309454]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_480.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -1.09995377]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_482.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -0.92726731]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_484.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44016048, -0.7636776]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_486.geometry}
        material={materials["Material.013"]}
        position={[0.52717978, 0.44088507, -1.79489207]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_488.geometry}
        material={materials["Material.013"]}
        position={[0.35185733, 0.44088507, -1.79489207]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_490.geometry}
        material={materials["Material.013"]}
        position={[0.16756432, 0.44088507, -1.79489207]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_492.geometry}
        material={materials["Material.013"]}
        position={[0.16756432, 0.44088507, -1.53572559]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_494.geometry}
        material={materials["Material.013"]}
        position={[0.16756432, 0.44088507, -1.19669807]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_496.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -0.58964884]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_498.geometry}
        material={materials["Material.013"]}
        position={[0.52930993, 0.44088507, -0.40167817]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.05558533, 0.05558533, 0.04568508]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_500.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -0.24157643]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_502.geometry}
        material={materials["Material.013"]}
        position={[0.52221304, 0.44088507, -0.06763941]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_504.geometry}
        material={materials["Material.013"]}
        position={[0.70684016, 0.44088507, -1.79489207]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_506.geometry}
        material={materials["Material.013"]}
        position={[0.90446401, 0.44088507, -1.76650953]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_508.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -0.67494446]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_510.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -0.84609079]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_512.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -1.01660848]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_514.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -1.1873486]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_516.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -1.35814083]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_518.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -0.50853199]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_520.geometry}
        material={materials["Material.013"]}
        position={[0.3427667, 0.44016048, -0.33473378]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05558533}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_522.geometry}
        material={materials["Material.013"]}
        position={[0.36702287, 0.44016048, -0.15340272]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_524.geometry}
        material={materials["Material.013"]}
        position={[0.36702287, 0.44016048, 0.01903351]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_526.geometry}
        material={materials["Material.013"]}
        position={[0.5480845, 0.44016048, 0.11069377]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_528.geometry}
        material={materials["Material.013"]}
        position={[0.16756432, 0.44088507, -0.16103232]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_530.geometry}
        material={materials["Material.013"]}
        position={[0.16756432, 0.43968916, 0.00244917]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_532.geometry}
        material={materials["Material.013"]}
        position={[0.90912682, 0.44088507, -1.58415389]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_534.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -1.42380393]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_536.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -1.41733706]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_538.geometry}
        material={materials["Material.013"]}
        position={[0.67098844, 0.44088507, -0.42518887]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_540.geometry}
        material={materials["Material.013"]}
        position={[0.67098844, 0.44088507, -0.2556197]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_542.geometry}
        material={materials["Material.013"]}
        position={[0.67098844, 0.44088507, -0.08538517]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_544.geometry}
        material={materials["Material.013"]}
        position={[0.67098844, 0.44088507, 0.08292352]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_546.geometry}
        material={materials["Material.013"]}
        position={[0.72874361, 0.44016048, 0.22638002]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_548.geometry}
        material={materials["Material.013"]}
        position={[0.6714195, 0.44016048, 0.22638002]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_550.geometry}
        material={materials["Material.013"]}
        position={[0.72874361, 0.44016048, 0.39841977]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_552.geometry}
        material={materials["Material.013"]}
        position={[0.6714195, 0.44016048, 0.39701393]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_554.geometry}
        material={materials["Material.013"]}
        position={[0.72874361, 0.44016048, 0.56919092]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_556.geometry}
        material={materials["Material.013"]}
        position={[0.6714195, 0.44016048, 0.57088476]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_558.geometry}
        material={materials["Material.013"]}
        position={[0.49254298, 0.44088507, -0.36410305]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_560.geometry}
        material={materials["Material.013"]}
        position={[0.49254298, 0.44088507, -0.193151]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_562.geometry}
        material={materials["Material.013"]}
        position={[0.49254298, 0.44088507, -0.02540557]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_564.geometry}
        material={materials["Material.013"]}
        position={[0.31626201, 0.44088507, -0.27539241]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03500688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_566.geometry}
        material={materials["Material.013"]}
        position={[0.53037941, 0.44088507, 0.5116818]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_568.geometry}
        material={materials["Material.013"]}
        position={[0.35580155, 0.44088507, 0.52902454]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_570.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -1.24846864]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04220521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_572.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -1.24720347]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_574.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -1.07730877]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04220521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_576.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -1.07601762]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_578.geometry}
        material={materials["Material.013"]}
        position={[1.03475666, 0.44088507, -1.79489207]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_580.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -0.91061348]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04220521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_582.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -0.90494573]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_584.geometry}
        material={materials["Material.013"]}
        position={[1.05579901, 0.44088507, 0.52339411]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_586.geometry}
        material={materials["Material.013"]}
        position={[0.88983095, 0.44088507, 0.45223746]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_588.geometry}
        material={materials["Material.013"]}
        position={[0.9180842, 0.44088507, 0.12955588]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_590.geometry}
        material={materials["Material.013"]}
        position={[0.90751773, 0.44088507, 0.29443818]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_592.geometry}
        material={materials["Material.013"]}
        position={[0.53868282, 0.44016048, 0.28521973]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_594.geometry}
        material={materials["Material.013"]}
        position={[0.36702287, 0.44016048, 0.19086745]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03991928}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_596.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -0.89301771]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_598.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -1.06745887]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_600.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -1.23406041]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_602.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -1.39708889]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_604.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -1.56929624]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_606.geometry}
        material={materials["Material.013"]}
        position={[1.05554128, 0.44088507, 0.36482811]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_608.geometry}
        material={materials["Material.013"]}
        position={[1.05554128, 0.44088507, 0.2149082]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_610.geometry}
        material={materials["Material.013"]}
        position={[1.05554128, 0.44088507, 0.03704809]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_612.geometry}
        material={materials["Material.013"]}
        position={[1.05554128, 0.44088507, -0.1310963]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_614.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -0.73295748]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_616.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -0.56886959]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_618.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -0.40451863]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_620.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -0.23785506]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_622.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, -0.09015159]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_624.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, 0.07925022]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_626.geometry}
        material={materials["Material.013"]}
        position={[1.01816833, 0.44088507, 0.2361539]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03603388}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_628.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -0.72999066]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04220521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_630.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -0.73190123]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_632.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -0.56452644]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04220521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_634.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -0.56166506]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_636.geometry}
        material={materials["Material.013"]}
        position={[0.91857147, 0.44088507, -0.39026302]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04220521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_638.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -0.39328068]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_640.geometry}
        material={materials["Material.013"]}
        position={[0.92765146, 0.44088507, -0.22157258]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.0422052, 0.0422052, 0.03469593]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_642.geometry}
        material={materials["Material.013"]}
        position={[0.94287592, 0.44088507, -0.02802441]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.0422052, 0.0422052, 0.03469593]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_644.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -0.22420947]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_646.geometry}
        material={materials["Material.013"]}
        position={[0.86315209, 0.44088507, -0.04904933]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04777842}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_648.geometry}
        material={materials["Material.013"]}
        position={[0.2161468, 0.43969932, 0.16345182]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_650.geometry}
        material={materials["Material.013"]}
        position={[0.2161468, 0.44088507, 0.53181005]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_652.geometry}
        material={materials["Material.013"]}
        position={[0.17929189, 0.44088507, 0.52395666]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.03976537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_654.geometry}
        material={materials.material_0}
        position={[0.88355696, 0.40260479, 0.91467243]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01137275}
      />
    </group>
  );
}

export default Laptop;
useGLTF.preload("/models/laptop.glb");
